CREATE EXTERNAL TABLE IF NOT EXISTS tidywigits.cider_vdj (
  `input_id` STRING,
  `input_prefix` STRING,
  `output_id` STRING,
  `cdr3_seq` STRING,
  `cdr3_aa` STRING,
  `locus` STRING,
  `filter` STRING,
  `blastn_status` STRING,
  `min_high_qual_base_reads` DOUBLE,
  `assigned_reads` DOUBLE,
  `v_aligned_reads` DOUBLE,
  `j_aligned_reads` DOUBLE,
  `in_frame` STRING,
  `contains_stop` STRING,
  `v_type` STRING,
  `v_anchor_start` DOUBLE,
  `v_anchor_end` DOUBLE,
  `v_anchor_seq` STRING,
  `v_anchor_template_seq` STRING,
  `v_anchor_aa` STRING,
  `v_anchor_template_aa` STRING,
  `v_match_method` STRING,
  `v_similarity_score` DOUBLE,
  `v_non_split_reads` DOUBLE,
  `j_type` STRING,
  `j_anchor_start` DOUBLE,
  `j_anchor_end` DOUBLE,
  `j_anchor_seq` STRING,
  `j_anchor_template_seq` STRING,
  `j_anchor_aa` STRING,
  `j_anchor_template_aa` STRING,
  `j_match_method` STRING,
  `j_similarity_score` DOUBLE,
  `j_non_split_reads` DOUBLE,
  `v_gene` STRING,
  `v_pident` DOUBLE,
  `v_align_start` DOUBLE,
  `v_align_end` DOUBLE,
  `d_gene` STRING,
  `d_pident` DOUBLE,
  `d_align_start` DOUBLE,
  `d_align_end` DOUBLE,
  `j_gene` STRING,
  `j_pident` DOUBLE,
  `j_align_start` DOUBLE,
  `j_align_end` DOUBLE,
  `v_primer_matches` DOUBLE,
  `j_primer_matches` DOUBLE,
  `layout_id` STRING,
  `full_seq` STRING,
  `support` STRING
)
PARTITIONED BY (
    batch_date string
)
STORED AS PARQUET
LOCATION 's3://derived-secondary-data-123456789123-ap-southeast-2-an/tidywigits/v1'
TBLPROPERTIES (
    'projection.enabled'='true',
    'projection.batch_date.type'='date',
    'projection.batch_date.range'='2026-01-01,NOW',
    'projection.batch_date.format'='yyyy-MM-dd',
    'storage.location.template'='s3://derived-secondary-data-123456789123-ap-southeast-2-an/tidywigits/v1/batch_date=${batch_date}/'
);
